// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/xdorro/golang-grpc-base-project/internal/module/user/biz"
	"github.com/xdorro/golang-grpc-base-project/internal/module/user/service"
	"github.com/xdorro/golang-grpc-base-project/internal/server"
	"github.com/xdorro/golang-grpc-base-project/internal/service"
	"github.com/xdorro/golang-grpc-base-project/pkg/repo"
)

// Injectors from wire.go:

func initServer() server.IServer {
	iRepo := repo.NewRepo()
	option := &userbiz.Option{
		Repo: iRepo,
	}
	iUserBiz := userbiz.NewBiz(option)
	userserviceOption := &userservice.Option{
		UserBiz: iUserBiz,
	}
	iUserService := userservice.NewService(userserviceOption)
	serviceOption := &service.Option{
		Repo:        iRepo,
		UserService: iUserService,
	}
	iService := service.NewService(serviceOption)
	serverOption := &server.Option{
		Service: iService,
	}
	iServer := server.NewServer(serverOption)
	return iServer
}
